### ISSUE TITLE
建议sql语句加入测试用户，在数据库增加了还得转换加密方式才行

### ISSUE THREAD

**Issue by lyseky** [scscms/vue-scscms#1]

**Comment by scscms** [comment]
您的意思是比如注册前，当用户输入用户名后立刻检查用户名是否有占用功能吗？

**Comment by lyseky** [comment]
我的意思是不想通过邮箱注册用户，默认一个admin的用户，后面可以改密码，mysql.sql只有创建表，没有插入数据

**Comment by scscms** [comment]
明白意思了：
`INSERT INTO user (user_name,pass_word,user_type,user_email) VALUES ('admin','$2a$10$oe/ovruYdv0EmNsKWLJwfu6Na51whOBRJOAJxBO.yt/C6DxQhdDNK',1,'10000@qq.com');`
已经写入server/mysql.sql文件；
