### ISSUE TITLE
431 (Request Header Fields Too Large)

### ISSUE THREAD

**Issue by dhj2020** [scscms/vue-scscms#11]
![image](https://user-images.githubusercontent.com/11954087/93868037-739f4f80-fcfc-11ea-8651-d065a29f04b3.png)
![image](https://user-images.githubusercontent.com/11954087/93868072-8023a800-fcfc-11ea-996a-df87f98b718b.png)

**Comment by scscms** [comment]
Node问题，从10.14版本开始头大小被限制不能超过8192字节。你百度一下解决方法。
