### ISSUE TITLE
登出后用户没有退出，还能打开其他页面

### ISSUE THREAD

**Issue by lowyjoe** [scscms/vue-scscms#2]
https://github.com/scscms/vue-scscms/blob/ccd8ca56b16a30d65fc83be76b763240356c3844/src/page/Home.vue#L323

**Comment by scscms** [comment]
谢谢。是退出仍能访问，退出时删除错了缓存。storage.remove('token');改为storage.remove('userInfo');

**Comment by lowyjoe** [comment]
嗯 为什么token需要这么删除啊？能给解释下吗？data: {
                            userInfo,
                            token: jwt.sign(Object.assign({ip}, userInfo),
                                config.JWTs.secret, {expiresIn: config.JWTs.expiresIn})
                        }
这块代码有token,为何在storage里面没有token这个属性呢？

**Comment by scscms** [comment]
token就是用户是否已登录的标志。token和用户信息合成一个对像存在locatStorage里。



guangda1234@126.com
 
发件人： liuyijiao
发送时间： 2018-03-21 14:36
收件人： scscms/vue-scscms
抄送： scscms; State change
主题： Re: [scscms/vue-scscms] 登出后用户没有退出，还能打开其他页面 (#2)
嗯 为什么token需要这么删除啊？能给解释下吗？data: {
userInfo,
token: jwt.sign(Object.assign({ip}, userInfo),
config.JWTs.secret, {expiresIn: config.JWTs.expiresIn})
}
这块代码有token,为何在storage里面没有token这个属性呢？

**Comment by lowyjoe** [comment]
嗯 谢谢
