### ISSUE TITLE
我又来了，关于配置的一点疑问

### ISSUE THREAD

**Issue by Zephylaci** [scscms/vue-scscms#4]
config/index.js 
server/common.js
这里面修改的两个ip是http服务的ip?
index dev里面有个port 是npm run dev用的端口？
于是问题来了..我npm run build 后npm run server 可以正常运行，各项功能正常..
但是npm run dev不知道是哪个设置的问题，前台ajax传不出来，直接canceled了..推测是跨域了..但我上面的地址全部设成一样的，端口也改成一样的，但就是不行，但是build后就能运行..不晓得是哪里的问题...
mysql..我读取你的mysql文件所有和时间有关的项都会出错..似乎和那个默认值有关，我全部把数据类型改成bigint存时间戳去了..我想问下，没有直接存时间戳是有什么考虑么？

**Comment by Zephylaci** [comment]
对了无关紧要的小bug..给超级管理员上传头像会变成普通用户...估计是数据更新的时候整体更新了...

**Comment by Zephylaci** [comment]
还有一个建议..api其实可以考虑每一个单独存一个文件.好改也好换...

**Comment by Zephylaci** [comment]
其它其实..经常有出现读取列表时报错，得刷新的情况...还有图片上传有的时候会出错但其实已经传上去了诸如此类的小问题....

**Comment by scscms** [comment]
1.赞同你的说法:api单独文件好管理。只是我这个demo只是做个例子，为初学者考虑，更好的用法由大家去扩展。
2.那你应该是在编辑用户里上传了头像（点头像来更新是不是有问题），我看了一下确实有bug。同时这引出一个安全问题来，一会修复。
3.关于端口是这样的：本程序是前后端分离系统，当你使用npm run dev时就是只运行前端，用于开发。其端口设置是在config/index.js里。而npm run build构建打包后，执行npm run server的是运行后端（同时可访问前端文件）其端口在app.js里设置。而server/common.js的web_domain端口也是指app.js里的。意思是访问后端接口的API地址，比如发邮件激活用户就要用到。总结起来就两个端口，一是仅前端，另一个是前后端一起用的。
4.至于时间戳问题当时没考虑什么，只是沿用了以前项目的mysql数据结构。

**Comment by Zephylaci** [comment]
如果说npm run dev只运行前端..那这个模式下...后端是完全没有响应的？那我想用npm run dev来开发的话，就得使用公用的api接口？因为本地没响应？我这么一改直接502了...

**Comment by w46245** [comment]
最后一条..我发现读取列表也好详细列表也罢非常容易出错...一开始以为是性能问题..后来看调试器发现是前台的ajax返回的是canceled...然而我搞不明白哪里会导致它触发这个..

**Comment by scscms** [comment]
如果你想开发同时运行后端，可以用两个npm窗口来分别执行npm run dev 和 npm run server 。另你要修改config/index.js为你自己的代理服务器。

**Comment by scscms** [comment]
这个问题应该是ajax超时引起。你修改一下超时设置即可：src/utils/ajax.js中的axios.defaults.timeout = 1000;//请求超时，适当修改。单位是毫秒！



guangda1234@126.com
 
发件人： zephyru
发送时间： 2018-04-09 22:05
收件人： scscms/vue-scscms
抄送： scscms; Comment
主题： Re: [scscms/vue-scscms] 我又来了，关于配置的一点疑问 (#4)
最后一条..我发现读取列表也好详细列表也罢非常容易出错...一开始以为是性能问题..后来看调试器发现是前台的ajax返回的是canceled...然而我搞不明白哪里会导致它触发这个..
―

**Comment by Zephylaci** [comment]
原来如此..我说dev和build后的端口为啥要错开呢..
后面那个我转眼就发现了..所以就删了..嘛，还是谢谢解答..暂时没别的问题了..

**Comment by ytianzaishui** [comment]
有没有考虑一下，把mysql配置抽取出来，而不是连接断开；另外，有没有考虑重构，引入Sequelize操作数据库，那就太棒了

**Comment by scscms** [comment]
最开始是考虑使用Sequelize的，但总感觉对象化后缺少写sql语句的乐趣，而且代码不明了对初学者很迷惑。二次开发者可以试试。mysq配置是独立的，只是连接数据库代码是否要独立成一个函数问题，当时有考虑。它连接过程因已经是模块封装过的，使用起来也就一行代码`const connection = await mysql.createConnection(config.mysqlDB);`。业务代码倒是有待重构。
这本身是一个入门级demo，简单，易懂最重要。
