### ISSUE TITLE
生产环境中，服务端如何打包部署呢

### ISSUE THREAD

**Issue by toadprince** [scscms/vue-scscms#5]
您好，服务端文件夹server会被打包吗？部署到生产环境是要把server源码拷贝过去用npm run server命令来实现启动服务端吗？

**Comment by scscms** [comment]
服务端执行的文件不会打包的。`npm run build`只打包前端代码。如果你在服务器里要同时运行前后端就全部代码拷贝过去。如果只想运行后端以下文件是必须的：
```
package.json
app.js
server-entry.js
node_modules/
config/
server/
```
