### ISSUE TITLE
生产环境中，游客如何访问

### ISSUE THREAD

**Issue by kun910202** [scscms/vue-scscms#7]
内容管理这些内容，网站中如何体现

**Comment by kun910202** [comment]
@scscms 我看内容管理系统好像还有个展示的入口，比如一个公司的网站后台内容管理系统，对应一个公司的网站。这块没看懂，谢谢

**Comment by scscms** [comment]
对，开放展示内容的块还没有做。也就是跟登录页一样没权限限制，把文章列表列出来并可查看详细。
列表需要美化，甚至做成瀑布流，可惜还没找到好设计。但实现展示不成问题。
